### ISSUE TITLE
Redémarage Leox LXT-010H-D

### ISSUE THREAD

**Issue by tompointexe** [StephanGR/gobox#11]
Hi everyone, Bonjour a tous
Depuis un mois environ, j'ai mon module Leox LXT-010H-D qui redémare aléatoirement, par fois il tient 10H, par fois 5 minutes
Je l'ai reconfiguré plusieurs fois avec Go-Box, super outil d'ailleurs, impossible de tenir plus de 72H fixe, c'est arrivé comme ça du jour au lendemain aprés plus de 1,8 An sans probléme, est-ce que sa vous ai deja arrivé ? que sa soit avec l'ont eth ou le module SFP ?
Merci d'avance pour l'aide

**Comment by iMord0** [comment]
I would try a firmware upgrade. I don't know with which version they come out now, but the latest I have on my drive is V3.3.4L4.
I can provide it to you or you can reach directly to Leox to get the newest one (let me know if there is one if you go this route).

You have to be on the same VLAN as leox module and go to http://X.X.X.X/upgrade.asp to upgrade
X.X.X.X is leox module IP

**Comment by tompointexe** [comment]
Hi, i have the ethernet module version, Marcin sent me the latest firmaware and the issue persists
I'm asking around if anyone is having the same issue as me, but i feel like it's an issue with the module, as the livebox itself does not have the issue
The module started to do this, and overheat / shutting down, adding a fan helps

**Comment by iMord0** [comment]
I must have misunderstood then since I used a translator. I see that you already figured it out, that's odd. Mine hasn't started to overheat after more than 2 years
