### ISSUE TITLE
Livbox v5 2Gb/s but limited 1Gb/s

### ISSUE THREAD

**Issue by lesmyrmidons** [StephanGR/gobox#12]
Hello,

I use UDM Pro SE and LEOX GPON STICK LXT-010S-H.
My subscription is a livebox v5 with 2Gb/s for download and 1Gb/s for upload.

But I'm stuck at 1gb/s, how can I upgrade to 2Gb/s?

**Comment by iMord0** [comment]
Hi,
I have unfortunate news for you, LEOX negotiates speed @ 1Gbps or 2.5Gbps. Unfortunately UDM Pro & UDM SE negotiate SFP only @ 1Gbps or 10Gbps so your only bet would be getting Ethernet not SFP leox device and using 2.5Gbps WAN port.

**Comment by Stoufiler** [comment]
Hello, 
@iMord0 has the good answer

Thanks

I close this issue
