### ISSUE TITLE
Demande de compatibilité de GO-BOX avec Sagemcom Fast 5670 pour GPON

### ISSUE THREAD

**Issue by cestmoibaptiste** [StephanGR/gobox#13]
Bonjour,

Je souhaite demander une compatibilité de GO-BOX avec la box **Sagemcom Fast 5670** (connue également sous le nom de  chez Orange).

Actuellement, GO-BOX fonctionne très bien avec certaines Livebox, mais il semble qu'il ne soit pas compatible avec la Sagemcom Fast 5670 pour récupérer le **GPON_SN** et le **PLOAM password**.

### Détails de la box :
- Modèle : Sagemcom Fast 5670 (Livebox 4)
- Utilisation : Connexion GPON fibre avec Orange (France)
- Accès via : http://192.168.0.1
- Protocole : GPON (G.984.3)
- Problème rencontré : GO-BOX se connecte à la box mais ne semble pas récupérer les informations GPON correctement. L'erreur `Can not unmarshal JSON` apparaît.

### Exemple d'informations attendues :
- **GPON_SN** (Numéro de série GPON)
- **PLOAM Password**

Je suis disponible pour fournir plus d'informations si nécessaire, ou tester de nouvelles versions du programme.

Merci pour votre travail et votre aide !

**Comment by Stoufiler** [comment]
Hello, 

Comme je l'ai déjà signifié dans d'autres issues, je ne suis actuellement plus chez Orange, de ce fait je ne peux pas débugger complètement le programme a moins d'avoir un accès au réseau distant par le biais d'un VPN.

A moins que vous m'autorisiez à accéder à votre réseau à distance, je ne pourrais pas travailler sur bug

Dans l'attente de vous lire
