### ISSUE TITLE
autre box internet et pfsense

### ISSUE THREAD

**Issue by GPConnect** [StephanGR/gobox#5]
Super boulot ! 
ta solution pourrait fonctionner avec d'autre box internet comme les ZTE ?
Est-ce que les informations récupérées peuvent également être paramétrer avec pfsense ? 
Merci

**Comment by Stoufiler** [comment]
Ooups ! J'avais pas vu ton issue !

Merci beaucoup !

Je pense que oui ca pourrait fonctionner mais n'ayant pas de box sous la main je ne pourrais pas te dire

Côté pfsense j'en ai jamais fait non plus mais ca doit pas être si compliqué !

Je pense qu'on pourrait même se connecter directement dessus et appliquer les commandes au lieu de simplement les afficher :)

**Comment by GPConnect** [comment]
n'ayant pas trouvé ton email, j'ai dû procéder ainsi :) désolé

**Comment by Stoufiler** [comment]
je n'ai pas bien compris ta réponse :/

**Comment by Stoufiler** [comment]
Je clos car pas de réponses
