### ISSUE TITLE
Can't unmarshal JSON on Livebox 6

### ISSUE THREAD

**Issue by Tresillo2017** [StephanGR/gobox#9]
After trying to use this tool with my Livebox 6 I get the following error
```
./GO-BOX --ip 192.168.1.1 --box livebox
Password : Can not unmarshal JSON

✅ Successfully connected to Livebox ! ✅
Can not unmarshal JSON
```
I've tried the latest compiled version and compiling from source but I've got the same error

**Comment by Stoufiler** [comment]
Hello, 

I don't have Livebox anymore so I can't debug the tool

I don't have people near to me where I can test

I Should add a --debug flag to print the json

**Comment by Tresillo2017** [comment]
Probably is caused due to a recent update to Livebox firmware.
I just want to get info out of that router so I can extract the sip info and get rid of it

**Comment by Stoufiler** [comment]
I made my tests on my old livebox 5 too

Maybe it's not the same OS

**Comment by Tresillo2017** [comment]
> I made my tests on my old livebox 5 too
> 
> Maybe it's not the same OS

Then no, livebox models change their firmware a lot and they patch things so its more difficult, but I don't think they use a really strong security, I might try some things but without any success since I don't know anything on this sector

**Comment by Stoufiler** [comment]
My tool, is not doing complicated things, it only make POST requests on the "API" and return the resulls

Maybe you can try to find the value you wanted with your browser dev tools

**Comment by Tresillo2017** [comment]
> My tool, is not doing complicated things, it only make POST requests on the "API" and return the resulls
> 
> Maybe you can try to find the value you wanted with your browser dev tools

I've been testing and any link that is inside /api will result in 401 doesn't matter if its exist or not. I think the api doesn't exist on livebox 6
![image](https://github.com/user-attachments/assets/4b6e665a-b4a5-47f8-bf73-a242af43525b)
